site_name: TESO-BodgeBot
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - admonition
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - navigation.sections